### ISSUE TITLE
Persist local storage based on users' wallet address

### ISSUE THREAD

**Issue by larrythecucumber321** [pickle-finance/pickle-ui#456] opened 2022-04-20 21:18 UTC
When switching wallets and refreshing the page, the UI will show the balances of the former wallet until the data is fully refreshed. This leads to a strange user experience where the user will check to see if they had actually switched wallets and realize the balances aren't reflective of the current wallet.

**Comment by janklimo** [comment] 2022-05-01 11:37
Duplicate of #448

**Closed by janklimo** 2022-05-01 11:37 UTC
